spring:
  application:
    name: SearchEmptySeat
  datasource:
    url: jdbc:postgresql://localhost:5432/ses
    username: ses
    password: ses#0987
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # none, update, create
    show-sql: true
jwt:
  secret: "7A85359EB855E16E6AA54AFCD271C71DC329074D922303EB41BD61E3F6BD21CD"  # JWT 서명에 사용할 비밀 키
  expiration: 3600000  # 만료 시간 (1시간 = 3600000ms)
